main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications & Posters
    url: publications/
    weight: 11
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
